spring:
  application:
    name: BusSimulation
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

agent:
  conf: agent.properties
  
bus:
  line: 509
  brigade: 1
  
api:
  um:
    url: https://api.um.warszawa.pl/api